name = "yich-beauty-system"
compatibility_date = "2026-05-24"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "yich-beauty-db"
database_id = "7939e88d-1606-4f10-a26f-c1276c7109f2"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "yich-beauty-system-assets"
