export const DEFAULT_AI_VIDEO_RESOLUTION = "480p" as const;

export const AI_VIDEO_PROVIDER_DEFAULT_RESOLUTIONS = {
  seedance: DEFAULT_AI_VIDEO_RESOLUTION,
  kling: DEFAULT_AI_VIDEO_RESOLUTION,
  hailuo: DEFAULT_AI_VIDEO_RESOLUTION,
  grok: DEFAULT_AI_VIDEO_RESOLUTION,
} as const;
