import type { AppData } from "./types";
import { nowIso, tomorrowAt } from "./utils";

export const seedData: AppData = {
  storeProfiles: [
    {
      id: "store1",
      name: "一宸 YiCh 皮肤管理中心",
      phone: "021-8888-0000",
      address: "上海市静安区示例路 88 号",
      businessHours: "10:00 - 21:00",
      createdAt: nowIso(),
    },
  ],
  authUsers: [
    { id: "u_owner", name: "林老板", account: "owner@demo.local", password: "yich-demo", role: "owner", roleName: "老板", status: "active", createdAt: nowIso() },
    { id: "u_manager", name: "林店长", account: "admin@demo.local", password: "yich-demo", role: "manager", roleName: "店长", staffId: "s1", status: "active", createdAt: nowIso() },
    { id: "u_frontdesk", name: "阿宁", account: "frontdesk@demo.local", password: "yich-demo", role: "frontdesk", roleName: "前台", staffId: "s3", status: "active", createdAt: nowIso() },
    { id: "u_therapist", name: "小雅", account: "therapist@demo.local", password: "yich-demo", role: "therapist", roleName: "美容师", staffId: "s2", status: "active", createdAt: nowIso() },
    { id: "u_finance", name: "财务", account: "finance@demo.local", password: "yich-demo", role: "finance", roleName: "财务", status: "active", createdAt: nowIso() },
  ],
  staffInvites: [],
  staff: [
    { id: "s1", name: "林店长", phone: "13800000001", role: "店长", status: "active", accountId: "u_manager", hiredAt: "2025-01-01", baseSalary: 9000, commissionRate: 0.12 },
    { id: "s2", name: "小雅", phone: "13800000002", role: "美容师", status: "active", accountId: "u_therapist", hiredAt: "2025-03-01", baseSalary: 6500, commissionRate: 0.12 },
    { id: "s3", name: "阿宁", phone: "13800000003", role: "前台", status: "active", accountId: "u_frontdesk", hiredAt: "2025-04-01", baseSalary: 6000, commissionRate: 0.04 },
  ],
  customers: [
    {
      id: "c1",
      name: "周女士",
      phone: "13600000001",
      level: "VIP",
      source: "老客转介绍",
      tags: ["敏感肌", "高复购"],
      lastVisit: nowIso(),
    },
    {
      id: "c2",
      name: "陈女士",
      phone: "13600000002",
      level: "普通会员",
      source: "抖音",
      tags: ["新客"],
      lastVisit: tomorrowAt(-24),
    },
    {
      id: "c3",
      name: "王女士",
      phone: "13600000003",
      level: "黑金会员",
      source: "私域社群",
      tags: ["高消费"],
      lastVisit: nowIso(),
    },
  ],
  services: [
    {
      id: "v1",
      name: "小气泡深层清洁",
      category: "皮肤管理",
      price: 398,
      duration: 60,
      consumableProductId: "p1",
      consumableQty: 1,
    },
    {
      id: "v2",
      name: "肩颈舒缓 SPA",
      category: "SPA 养生",
      price: 268,
      duration: 45,
      consumableProductId: "p2",
      consumableQty: 0.5,
    },
    {
      id: "v3",
      name: "产后修复调理",
      category: "产后康复",
      price: 680,
      duration: 90,
      consumableProductId: "p3",
      consumableQty: 1,
    },
  ],
  products: [
    { id: "p1", name: "清洁精华液", type: "consumable", unit: "瓶", price: 128, cost: 65, stock: 18, warningStock: 5 },
    { id: "p2", name: "草本按摩油", type: "consumable", unit: "瓶", price: 168, cost: 80, stock: 12, warningStock: 4 },
    { id: "p3", name: "修复护理包", type: "consumable", unit: "套", price: 298, cost: 150, stock: 9, warningStock: 3 },
    { id: "p4", name: "家用补水面膜", type: "sale", unit: "盒", price: 199, cost: 92, stock: 24, warningStock: 8 },
  ],
  appointments: [
    { id: "a1", customerId: "c1", staffId: "s2", serviceId: "v1", startAt: tomorrowAt(10), status: "已确认", note: "做完需回访" },
    { id: "a2", customerId: "c3", staffId: "s1", serviceId: "v3", startAt: tomorrowAt(14), status: "待确认", note: "老客套餐咨询" },
  ],
  staffUnavailableSlots: [],
  staffShifts: [
    { id: "ss1", staffId: "s1", startAt: tomorrowAt(9), endAt: tomorrowAt(21), note: "标准早晚班", createdBy: "u_manager", createdAt: nowIso() },
    { id: "ss2", staffId: "s2", startAt: tomorrowAt(9), endAt: tomorrowAt(21), note: "标准早晚班", createdBy: "u_manager", createdAt: nowIso() },
    { id: "ss3", staffId: "s3", startAt: tomorrowAt(9), endAt: tomorrowAt(21), note: "标准早晚班", createdBy: "u_manager", createdAt: nowIso() },
  ],
  memberCards: [
    { id: "m1", customerId: "c1", name: "尊享储值卡", type: "储值卡", balance: 2600, remainingTimes: 0, expiresAt: "2027-12-31", status: "正常" },
    {
      id: "m2",
      customerId: "c3",
      name: "小气泡 10 次卡",
      type: "次数卡",
      balance: 0,
      remainingTimes: 6,
      expiresAt: "2027-06-30",
      status: "正常",
      serviceId: "v1",
      serviceIds: ["v1"],
    },
  ],
  orders: [],
  refunds: [],
  commissions: [],
  inventoryLogs: [],
  memberCardTransactions: [],
  operationLogs: [],
  dailyCloses: [],
  approvalRequests: [],
  customerServiceRecords: [],
  customerFollowUps: [],
  suppliers: [
    { id: "sp1", name: "一宸耗材供应商", phone: "021-6666-0000", contact: "张经理", status: "active" },
  ],
  purchaseOrders: [],
  stocktakes: [],
};
