import type { AppData } from "./types";
import { defaultSystemConfigs } from "./business";

export const seedData: AppData = {
  storeProfiles: [],
  onlineStorefronts: [],
  authUsers: [
    {
      id: "u_superadmin",
      name: "平台管理员",
      account: "admin@yich.local",
      password: "admin123456",
      role: "superadmin",
      roleName: "系统管理员",
      status: "active",
      createdAt: "2026-05-30T00:00:00.000Z",
    },
  ],
  staffInvites: [],
  storeOwnerInvites: [],
  storeOwnerApplications: [],
  staff: [],
  customers: [],
  tagDefinitions: [],
  services: [],
  products: [],
  inventoryBatches: [],
  appointments: [],
  onlineBookingRequests: [],
  staffUnavailableSlots: [],
  staffShifts: [],
  memberCards: [],
  distributors: [],
  referralRelations: [],
  orders: [],
  refunds: [],
  commissions: [],
  distributionCommissions: [],
  commissionSettlements: [],
  inventoryLogs: [],
  memberCardTransactions: [],
  operationLogs: [],
  marketingAiRecords: [],
  systemConfigs: defaultSystemConfigs({ now: () => "2026-05-30T00:00:00.000Z" }),
  notifications: [],
  dailyCloses: [],
  approvalRequests: [],
  customerServiceRecords: [],
  customerSignatures: [],
  customerFollowUps: [],
  suppliers: [],
  purchaseOrders: [],
  stocktakes: [],
};
