import type { AppData } from "./types";
import { defaultSystemConfigs } from "./business";
import { nowIso, tomorrowAt } from "./utils";

export const testFixtureData: AppData = {
  storeProfiles: [
    {
      id: "store1",
      name: "祝融｜坤锋美学门店",
      phone: "021-8888-0000",
      address: "上海市静安区示例路 88 号",
      businessHours: "10:00 - 21:00",
      status: "active",
      createdAt: nowIso(),
    },
  ],
  onlineStorefronts: [
    {
      id: "os1",
      storeId: "store1",
      shareCode: "yich-store",
      status: "启用",
      headline: "祝融｜坤锋 美业门店系统",
      description: "线上查看项目并提交到店预约意向",
      enabledServiceIds: ["v1", "v2", "v3"],
      createdAt: nowIso(),
      updatedAt: nowIso(),
    },
  ],
  authUsers: [
    { id: "u_superadmin", name: "平台管理员", account: "admin@test.local", password: "test-password", role: "superadmin", roleName: "Admin", status: "active", createdAt: nowIso() },
    { id: "u_owner", name: "林老板", account: "owner@test.local", password: "test-password", role: "owner", roleName: "老板", status: "active", createdAt: nowIso() },
    { id: "u_manager", name: "林主管", account: "manager@test.local", password: "test-password", role: "manager", roleName: "主管", staffId: "s1", status: "active", createdAt: nowIso() },
    { id: "u_frontdesk", name: "阿宁", account: "frontdesk@test.local", password: "test-password", role: "frontdesk", roleName: "前台", staffId: "s3", status: "active", createdAt: nowIso() },
    { id: "u_therapist", name: "小雅", account: "therapist@test.local", password: "test-password", role: "therapist", roleName: "员工", staffId: "s2", status: "active", createdAt: nowIso() },
    { id: "u_finance", name: "财务", account: "finance@test.local", password: "test-password", role: "finance", roleName: "财务", status: "active", createdAt: nowIso() },
  ],
  staffInvites: [],
  storeOwnerInvites: [],
  storeOwnerApplications: [],
  staff: [
    { id: "s1", name: "林主管", phone: "13800000001", role: "主管", status: "active", accountId: "u_manager", hiredAt: "2025-01-01", baseSalary: 9000, commissionRate: 0.12 },
    { id: "s2", name: "小雅", phone: "13800000002", role: "员工", status: "active", accountId: "u_therapist", hiredAt: "2025-03-01", baseSalary: 6500, commissionRate: 0.12 },
    { id: "s3", name: "阿宁", phone: "13800000003", role: "前台", status: "active", accountId: "u_frontdesk", hiredAt: "2025-04-01", baseSalary: 6000, commissionRate: 0.04 },
  ],
  customers: [
    {
      id: "c1",
      name: "周女士",
      phone: "13600000001",
      level: "VIP",
      source: "老客转介绍",
      tags: ["敏感肌", "高复购"],
      lastVisit: nowIso(),
    },
    {
      id: "c2",
      name: "陈女士",
      phone: "13600000002",
      level: "普通会员",
      source: "线上预约",
      tags: ["新客"],
      lastVisit: tomorrowAt(-24),
    },
    {
      id: "c3",
      name: "王女士",
      phone: "13600000003",
      level: "黑金会员",
      source: "私域社群",
      tags: ["高消费"],
      lastVisit: nowIso(),
    },
  ],
  tagDefinitions: [
    { id: "tag1", name: "敏感肌", scope: "客户", color: "#7c3aed", status: "启用", createdAt: nowIso() },
    { id: "tag2", name: "高复购", scope: "客户", color: "#db2777", status: "启用", createdAt: nowIso() },
    { id: "tag3", name: "新客", scope: "客户", color: "#0d9488", status: "启用", createdAt: nowIso() },
    { id: "tag4", name: "高消费", scope: "客户", color: "#b45309", status: "启用", createdAt: nowIso() },
    { id: "tag5", name: "皮肤管理", scope: "项目", color: "#6d28d9", status: "启用", createdAt: nowIso() },
    { id: "tag6", name: "SPA养生", scope: "项目", color: "#be185d", status: "启用", createdAt: nowIso() },
    { id: "tag7", name: "手法稳定", scope: "员工", color: "#047857", status: "启用", createdAt: nowIso() },
  ],
  services: [
    {
      id: "v1",
      name: "小气泡深层清洁",
      category: "皮肤管理",
      price: 398,
      duration: 60,
      consumables: [{ productId: "p1", quantity: 1 }],
      consumableProductId: "p1",
      consumableQty: 1,
    },
    {
      id: "v2",
      name: "肩颈舒缓 SPA",
      category: "SPA 养生",
      price: 268,
      duration: 45,
      consumables: [{ productId: "p2", quantity: 0.5 }],
      consumableProductId: "p2",
      consumableQty: 0.5,
    },
    {
      id: "v3",
      name: "产后修复调理",
      category: "产后康复",
      price: 680,
      duration: 90,
      consumables: [{ productId: "p3", quantity: 1 }],
      consumableProductId: "p3",
      consumableQty: 1,
    },
  ],
  products: [
    { id: "p1", name: "清洁精华液", type: "sale", category: "面护类", subcategory: "精华", unit: "瓶", price: 128, cost: 65, stock: 18, warningStock: 5, shelfLifeMonths: 24 },
    { id: "p2", name: "草本按摩油", type: "sale", category: "养生类", subcategory: "身体油", unit: "瓶", price: 168, cost: 80, stock: 12, warningStock: 4, shelfLifeMonths: 24 },
    { id: "p3", name: "修复护理包", type: "sale", category: "养生类", subcategory: "套盒", unit: "套", price: 298, cost: 150, stock: 9, warningStock: 3, shelfLifeMonths: 24 },
    { id: "p4", name: "家用补水面膜", type: "sale", category: "面护类", subcategory: "面膜", unit: "盒", price: 199, cost: 92, stock: 24, warningStock: 8, shelfLifeMonths: 24 },
  ],
  inventoryBatches: [],
  appointments: [
    { id: "a1", customerId: "c1", staffId: "s2", serviceId: "v1", startAt: tomorrowAt(10), roomName: "护理房 1", status: "已确认", note: "做完需回访" },
    { id: "a2", customerId: "c3", staffId: "s1", serviceId: "v3", startAt: tomorrowAt(14), roomName: "VIP护理房", status: "待确认", note: "老客套餐咨询" },
  ],
  onlineBookingRequests: [],
  staffUnavailableSlots: [],
  staffShifts: [
    { id: "ss1", staffId: "s1", startAt: tomorrowAt(9), endAt: tomorrowAt(21), note: "标准早晚班", createdBy: "u_manager", createdAt: nowIso() },
    { id: "ss2", staffId: "s2", startAt: tomorrowAt(9), endAt: tomorrowAt(21), note: "标准早晚班", createdBy: "u_manager", createdAt: nowIso() },
    { id: "ss3", staffId: "s3", startAt: tomorrowAt(9), endAt: tomorrowAt(21), note: "标准早晚班", createdBy: "u_manager", createdAt: nowIso() },
  ],
  memberCards: [
    { id: "m1", customerId: "c1", name: "尊享储值卡", type: "储值卡", balance: 2600, remainingTimes: 0, expiresAt: "2027-12-31", status: "正常" },
    {
      id: "m2",
      customerId: "c3",
      name: "小气泡 10 次卡",
      type: "次数卡",
      balance: 0,
      remainingTimes: 6,
      expiresAt: "2027-06-30",
      status: "正常",
      serviceId: "v1",
      serviceIds: ["v1"],
    },
  ],
  distributors: [
    {
      id: "d1",
      type: "客户",
      customerId: "c1",
      name: "周女士",
      phone: "13600000001",
      rate: 0.08,
      status: "启用",
      inviteCode: "ZRKF-C1",
      createdAt: nowIso(),
    },
  ],
  referralRelations: [
    {
      id: "rr1",
      distributorId: "d1",
      customerId: "c2",
      source: "手工绑定",
      status: "有效",
      createdAt: nowIso(),
    },
  ],
  orders: [],
  refunds: [],
  commissions: [],
  distributionCommissions: [],
  commissionSettlements: [],
  inventoryLogs: [],
  memberCardTransactions: [],
  operationLogs: [],
  systemConfigs: defaultSystemConfigs(),
  notifications: [],
  dailyCloses: [],
  approvalRequests: [],
  customerServiceRecords: [],
  customerSignatures: [],
  customerFollowUps: [],
  suppliers: [
    { id: "sp1", name: "祝融｜坤锋商品供应商", phone: "021-6666-0000", contact: "张经理", status: "active" },
  ],
  purchaseOrders: [],
  stocktakes: [],
};
