CREATE INDEX IF NOT EXISTS idx_staff_store ON staff(storeId);
CREATE INDEX IF NOT EXISTS idx_customers_store_last_visit ON customers(storeId, lastVisit);
CREATE INDEX IF NOT EXISTS idx_customers_store_phone ON customers(storeId, phone);
CREATE INDEX IF NOT EXISTS idx_services_store_status ON services(storeId, status);
CREATE INDEX IF NOT EXISTS idx_products_store_status ON products(storeId, status);
CREATE INDEX IF NOT EXISTS idx_products_store_category ON products(storeId, category, subcategory);
CREATE INDEX IF NOT EXISTS idx_appointments_store_start ON appointments(storeId, startAt);
CREATE INDEX IF NOT EXISTS idx_appointments_store_status ON appointments(storeId, status);
CREATE INDEX IF NOT EXISTS idx_appointments_store_staff_start ON appointments(storeId, staffId, startAt);
CREATE INDEX IF NOT EXISTS idx_member_cards_store_customer ON memberCards(storeId, customerId);
CREATE INDEX IF NOT EXISTS idx_member_cards_store_status ON memberCards(storeId, status);
CREATE INDEX IF NOT EXISTS idx_orders_store_created ON orders(storeId, createdAt);
CREATE INDEX IF NOT EXISTS idx_orders_store_customer_created ON orders(storeId, customerId, createdAt);
CREATE INDEX IF NOT EXISTS idx_orders_store_staff_created ON orders(storeId, staffId, createdAt);
CREATE INDEX IF NOT EXISTS idx_refunds_store_created ON refunds(storeId, createdAt);
CREATE INDEX IF NOT EXISTS idx_inventory_logs_store_created ON inventoryLogs(storeId, createdAt);
CREATE INDEX IF NOT EXISTS idx_inventory_logs_store_product_created ON inventoryLogs(storeId, productId, createdAt);
CREATE INDEX IF NOT EXISTS idx_member_card_transactions_store_created ON memberCardTransactions(storeId, createdAt);
CREATE INDEX IF NOT EXISTS idx_operation_logs_store_created ON operationLogs(storeId, createdAt);
CREATE INDEX IF NOT EXISTS idx_daily_closes_store_date ON dailyCloses(storeId, businessDate);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(userId);
CREATE INDEX IF NOT EXISTS idx_checkout_locks_created ON checkoutSubmissionLocks(createdAt);
CREATE INDEX IF NOT EXISTS idx_auth_users_store_json ON authUsers(json_extract(payload_json, '$.storeId'));
CREATE INDEX IF NOT EXISTS idx_auth_users_account_json ON authUsers(json_extract(payload_json, '$.account'));
CREATE INDEX IF NOT EXISTS idx_notifications_store_json ON notifications(json_extract(payload_json, '$.storeId'));
